### ISSUE TITLE
Difference between GML from file and GML from WFS - inheritance

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/caniuse#16]
The tests should differentiate between GML loaded from a file and GML served by WFS. In QGIS, it is apparently a complete different part of the source code that handles that, so the results can be completely different.

One example is the handling of inheritance. E.g. when the geometry is defined on the supertype, geometries are not rendered at all.

See e.g. the service described at https://geodata-info.dk/srv/eng/catalog.search#/metadata/8e82f1df-1352-4375-83ce-503aa8425661 (the first link).

**Comment by sMorrone** [comment]
I tried the link you provided: I am able to connect to WFS ("http://kortforsyningen.kms.dk/ra_tn_elf_gml321?") both from QGIS2.18 and from QGIS3.4. Geometries are correctly displayed and info is correct + it is same info displayed in the case of GML. In the case of QGIS 3.4, however, I have to specify the wfs version in the connection URL to make it work (see attached screenshot).
![2019-06-05 (4)](https://user-images.githubusercontent.com/13329248/58973558-88329e00-87c0-11e9-907d-8060ceccdfc1.png)

**Comment by heidivanparys** [comment]
I investigated again. The scenario I described is without the use of the GML application toolbox plugin,

![image](https://user-images.githubusercontent.com/11427611/62611336-a8d4bc80-b905-11e9-8fec-aa6810d2c0da.png)

![image](https://user-images.githubusercontent.com/11427611/62611389-c2760400-b905-11e9-9793-b648dccac4b2.png)
 
The geometry is defined on the supertype, tn-ra:RailwayLink, and not on elf:RailwayLink, and then QGIS doesn't recognize the geometries.

I tried also with the GML application toolbox plugin, in QGIS 3.4.10, but I get a Python error, and nothing is shown. Probably the same as described in https://github.com/BRGM/gml_application_schema_toolbox/issues/88

```
AttributeError: 'NoneType' object has no attribute 'split' 
Traceback (most recent call last):
  File "C:/Users/B004114/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_wfs.py", line 135, in on_connectBtn_clicked
    return self.on_connectBtn_clicked_()
  File "C:/Users/B004114/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_wfs.py", line 137, in on_connectBtn_clicked_
    wfs = self.wfs()
  File "C:/Users/B004114/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_wfs.py", line 118, in wfs
    with qgis_proxy_settings():
  File "C:/Users/B004114/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\proxy.py", line 30, in __enter__
    excludes = excludes.split("|")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by sMorrone** [comment]
Thank you Heidi for your follow-up.
To consume WFS 2.0 serving **complex features** you **need** to use the GML application toolbox plugin. Unfortunately no support is provided out of the box.
That said, using the plugin, I am still able to load your data as well as the data from WFS link in [BRGM/gml_application_schema_toolbox#88](url) -as you can see respectively from screenshot 1, 2 and 3.
I am neither able to reproduce your issue nor to obtain your error message. So I guess the system configuration options are involved somehow (I am using Windows 10 - GDAL 2.4 - Gml Application schema version 1.2.0
![2019-08-26 screenshot1](https://user-images.githubusercontent.com/13329248/63683971-1e90c180-c7fc-11e9-9ed0-18433146e244.png)
![2019-08-26 screenshot2](https://user-images.githubusercontent.com/13329248/63683986-27819300-c7fc-11e9-881a-089bd1828fe5.png)
![2019-08-26 screenshot3](https://user-images.githubusercontent.com/13329248/63684148-7f1ffe80-c7fc-11e9-9029-d2356d0a04dc.png)


.
